### ISSUE TITLE
nothing happend at boot

### ISSUE THREAD

**Issue by goliwok** [wrzlbrmft/arch-pi#1]
hi, 
when i plug the sd and start rp, nothing happend ..
the screen stay black .

do you have ideas ?

**Comment by wrzlbrmft** [comment]
Hi! Without knowing any details it could be pretty much anything. Have you switched on the screen?
Just kidding. But help me to help you:
- What Pi do you have?
- Can you send me the config file you used?
- What have you selected during install (which Pi model)?
- Can you send me the console output of the script?
Thanks,
Matt

**Comment by goliwok** [comment]
oh yeah sorry ..
indeed without details it's difficult..

I have a pi 3 model B (so i selected "3") .

there you are log during install (sorry for french output) :
[log.txt](https://github.com/wrzlbrmft/arch-pi/files/730951/log.txt)

and there the conf file (in .txt for upload it)
[arch-pi.txt](https://github.com/wrzlbrmft/arch-pi/files/730956/arch-pi.txt)

thanks for your help !

**Comment by wrzlbrmft** [comment]
My french is not that good, but using Google Translate "mkfs: échec d'exécution de mkfs.fat: Aucun fichier ou dossier de ce type" means that it was not able to create a FAT (vfat) filesystem. Please verify if you have support for FAT filesystems installed. You can do so using:

`which mkfs.fat`

The boot partition for a Raspberry Pi is supposed to be a FAT32 file system.

**Comment by goliwok** [comment]
Ok, i did not have msdosfstools on my arch ..
Thank you for helping !

**Comment by wrzlbrmft** [comment]
Cool, have fun!
